### ISSUE TITLE
Code generation for external types

### ISSUE THREAD

**Issue by mattunlv** [mattunlv/ProcessJ-Compiler#19]
darkwing:ProcessJ matt$ more externtest.pj

import std.io;
import std.number;

public proc void main(string args[])[yield=true] {
   Integer i;
   i = makeInteger(7);
   int j = getValueInteger(i);
   println(j);   

}
darkwing:ProcessJ matt$ more Include/JVM/std/number.pj
#pragma LIBRARY;
#pragma NATIVE;
#pragma FILE "number";
#pragma LANGUAGE "JVM";
package std;

extern java.lang.Integer Integer

public proc Integer makeInteger(int value) ;

public proc int getValueInteger(Integer i) ;            
--------------------------------------------------------------
darkwing:ProcessJ matt$ more Lib/JVM/std/number.java
package std;

public class number {
    public static java.lang.Integer makeInteger(int value) {
        return new java.lang.Integer(value);
    }
    
    public static int getValueInteger(java.lang.Integer i) {
        return i.intValue();
    }
}
--------------------------------------------------------------
darkwing:ProcessJ matt$ more externtest.pj

import std.io;
import std.number;

public proc void main(string args[])[yield=true] {
   Integer i;
   i = makeInteger(7);
   int j = getValueInteger(i);
   println(j);   
}
--------------------------------------------------------------
generates:

 public static class procMain extends PJProcess {
                String[] _pd$args;
                null _ld1$i;
                int _ld2$j;

            public procMain(String[] _pd$args) {
                this._pd$args = _pd$args;
            }
    ...

the null is wrong - I should be the  extern type name (here; java.lang.Integer)

**Comment by cabelshrestha** [comment]
Fixed and the code has been pushed into master.

**Comment by mattunlv** [comment]
Hey Cabel,

when you say ‘fixed’ are you referring to that strange bug that I cannot for the life of me explain ????

*fingers*crossed* cause we are DEAD in the water right now … 

Matt


***************************************************************************
* Jan 'Matt' Pedersen, Ph.D.             Office: TBE B384                 *
* Associate Professor                    E-mail: matt.pedersen@unlv.edu <mailto:matt.pedersen@unlv.edu>   *
* School of Computer Science             Phone : +1 (702) 895-2557        *
* University of Nevada at Las Vegas      Fax   : +1 (702) 895-2639        *
* Las Vegas, NV, 89154-4019                                               *
*                                                                         *
*               Home Page: http://www.egr.unlv.edu/~matt <http://www.cs.unlv.edu/~matt>                  *
*                                                                         *
* Note: This email is meant for the original recipients only - that means *
* that you may NOT forward it to anyone nor include it as part of a reply *
* to me if that reply involves recipients not part of the original email. *
***************************************************************************
