### ISSUE TITLE
Deadlock..

### ISSUE THREAD

**Issue by mattunlv** [mattunlv/ProcessJ-Compiler#9]
This will deadlock:
import std.io;

proc void hello() {
  println("Hello");
}

proc void world() {
  println("World");
}

proc void main(string args[]) [yield=true] {
  par {
    hello();
    world();
  }
  println("Good bye");
}

if hello and world does not have [yield=true] … I don't know if this is my problem ;-)

**Comment by cabelshrestha** [comment]
I haven't tried it, but looks like that will deadlock as the main proc waits for the par items to decrement its count and set it ready...but hello and world procs do not have a terminate method to do so.

How do we want to handle this?

**Comment by cabelshrestha** [comment]
Fixed using 'anonymous' process wrap.
